; AutoHotkey v2 Script for Anki Global Hotkeys - Version 3 (ControlSend Method)
; Generated by Anki Global Hotkey Card Control addon

; This version uses ControlSend to send keys directly to Anki without needing window focus
; Uses Anki's built-in review shortcuts: 1=Again, 3=Good, O=Options

; Global hotkeys for Anki card review
; These work regardless of which window has focus

; Ctrl+Z -> Score card as Good (sends "3" key)
^z::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "3" key directly to Anki (Good rating)
        ControlSend("3", , "ahk_exe anki.exe")
    }
}

; Ctrl+X -> Score card as Again (sends "1" key)
^x::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "1" key directly to Anki (Again rating)
        ControlSend("1", , "ahk_exe anki.exe")
    }
}

; Ctrl+O -> Options (sends "O" key)
^o::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "o" key directly to Anki (Options)
        ControlSend("o", , "ahk_exe anki.exe")
    }
}

; Test hotkey for debugging (Ctrl+Alt+T)
^!t::
{
    ; Send a simple message box to verify AHK is working
    MsgBox("AutoHotkey v3 ControlSend Method is running!`nProcess ID: " . ProcessExist() . "`nAnki detected: " . (WinExist("ahk_exe anki.exe") ? "Yes" : "No"))
}

; Diagnostic hotkey (Ctrl+Alt+D) - Test sending "3" key
^!d::
{
    if (WinExist("ahk_exe anki.exe"))
    {
        ControlSend("3", , "ahk_exe anki.exe")
        MsgBox("Sent '3' key to Anki via ControlSend (should score card as Good)")
    }
    else
    {
        MsgBox("Anki not detected - make sure Anki is running")
    }
}

; Exit hotkey for cleanup (Ctrl+Alt+Q)
^!q::ExitApp()