; AutoHotkey v2 Script for Anki Global Hotkeys - Version 2 (Enhanced Qt Method)
; Generated by Anki Global Hotkey Card Control addon

; Global hotkeys for Anki card review
; These work regardless of which window has focus

; Ctrl+Z -> Score card as Good
^z::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Activate Anki window
        WinActivate("ahk_exe anki.exe")
        ; Wait for window activation
        Sleep(150)
        ; Send F13 key which Anki will catch with Qt shortcuts
        Send("{F13}")
    }
}

; Ctrl+X -> Score card as Again
^x::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Activate Anki window
        WinActivate("ahk_exe anki.exe")
        ; Wait for window activation
        Sleep(150)
        ; Send F14 key which Anki will catch with Qt shortcuts
        Send("{F14}")
    }
}

; Ctrl+O -> Toggle always on top
^o::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Activate Anki window
        WinActivate("ahk_exe anki.exe")
        ; Wait for window activation
        Sleep(150)
        ; Send F15 key which Anki will catch with Qt shortcuts
        Send("{F15}")
    }
}

; Test hotkey for debugging (Ctrl+Alt+T)
^!t::
{
    ; Send a simple message box to verify AHK is working
    MsgBox("AutoHotkey v2 Qt Method is running!`nProcess ID: " . ProcessExist() . "`nAnki detected: " . (WinExist("ahk_exe anki.exe") ? "Yes" : "No"))
}

; Diagnostic hotkey (Ctrl+Alt+D) - Test F13 key sending
^!d::
{
    if (WinExist("ahk_exe anki.exe"))
    {
        WinActivate("ahk_exe anki.exe")
        Sleep(150)
        Send("{F13}")
        MsgBox("Sent F13 key to Anki (should trigger Good if Qt shortcuts working)")
    }
    else
    {
        MsgBox("Anki not detected - make sure Anki is running")
    }
}

; Exit hotkey for cleanup (Ctrl+Alt+Q)
^!q::ExitApp()