; AutoHotkey v2 Script for Anki Global Hotkeys - Version 4 (PostMessage Method)
; Generated by Anki Global Hotkey Card Control addon

; This version uses PostMessage to send Windows messages directly to Anki
; Uses WM_KEYDOWN (0x100) and WM_KEYUP (0x101) messages
; Sends Anki's built-in review shortcuts: 1=Again, 3=Good, O=Options

; Global hotkeys for Anki card review
; These work regardless of which window has focus

; Ctrl+Z -> Score card as Good (sends "3" key via Windows messages)
^z::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "3" key via Windows messages (Good rating)
        ; 0x33 = Virtual key code for "3"
        PostMessage(0x100, 0x33, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN
        Sleep(50)
        PostMessage(0x101, 0x33, 0, , "ahk_exe anki.exe")  ; WM_KEYUP
    }
}

; Ctrl+X -> Score card as Again (sends "1" key via Windows messages)
^x::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "1" key via Windows messages (Again rating)
        ; 0x31 = Virtual key code for "1"
        PostMessage(0x100, 0x31, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN
        Sleep(50)
        PostMessage(0x101, 0x31, 0, , "ahk_exe anki.exe")  ; WM_KEYUP
    }
}

; Ctrl+O -> Options (sends "O" key via Windows messages)
^o::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "O" key via Windows messages (Options)
        ; 0x4F = Virtual key code for "O"
        PostMessage(0x100, 0x4F, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN
        Sleep(50)
        PostMessage(0x101, 0x4F, 0, , "ahk_exe anki.exe")  ; WM_KEYUP
    }
}

; Test hotkey for debugging (Ctrl+Alt+T)
^!t::
{
    ; Send a simple message box to verify AHK is working
    MsgBox("AutoHotkey v4 PostMessage Method is running!`nProcess ID: " . ProcessExist() . "`nAnki detected: " . (WinExist("ahk_exe anki.exe") ? "Yes" : "No"))
}

; Diagnostic hotkey (Ctrl+Alt+D) - Test sending "3" key via PostMessage
^!d::
{
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send "3" key via PostMessage
        PostMessage(0x100, 0x33, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN
        Sleep(50)
        PostMessage(0x101, 0x33, 0, , "ahk_exe anki.exe")  ; WM_KEYUP
        MsgBox("Sent '3' key to Anki via PostMessage (should score card as Good)")
    }
    else
    {
        MsgBox("Anki not detected - make sure Anki is running")
    }
}

; Exit hotkey for cleanup (Ctrl+Alt+Q)
^!q::ExitApp()