; AutoHotkey v2 Script for Anki Global Hotkeys
; Generated by Anki Global Hotkey Card Control addon

; Global hotkeys for Anki card review
; These work regardless of which window has focus
; Uses SendMessage to send standard keyboard keys to Anki process
; Key codes: 0x20 (Spacebar), 0x31 ('1'), 0x33 ('3')

; Ctrl+Shift -> Show Answer (send Spacebar)
^+a::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send Spacebar via SendMessage for "Show Answer"
        ; 0x20 is the virtual key code for Spacebar
        SendMessage(0x100, 0x20, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN for Spacebar
        SendMessage(0x101, 0x20, 0, , "ahk_exe anki.exe")  ; WM_KEYUP for Spacebar
    }
}

; Ctrl+Z -> Score card as Again (send '1' key)
^z::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send '1' key via SendMessage for "Again" score
        ; 0x31 is the virtual key code for '1'
        SendMessage(0x100, 0x31, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN for '1'
        SendMessage(0x101, 0x31, 0, , "ahk_exe anki.exe")  ; WM_KEYUP for '1'
    }
}

; Ctrl+X -> Score card as Good (send '3' key)
^x::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send '3' key via SendMessage for "Good" score
        ; 0x33 is the virtual key code for '3'
        SendMessage(0x100, 0x33, 0, , "ahk_exe anki.exe")  ; WM_KEYDOWN for '3'
        SendMessage(0x101, 0x33, 0, , "ahk_exe anki.exe")  ; WM_KEYUP for '3'
    }
}

; Ctrl+O -> Toggle always on top (legacy - no longer used)
; ^o::
; {
;     ; This functionality has been removed for simplicity
; }

; Exit hotkey for cleanup (Ctrl+Alt+Q)
^!q::ExitApp()

; Test hotkey for debugging (Ctrl+Alt+T)
^!t::
{
    ; Send a simple message box to verify AHK is working
    if (WinExist("ahk_exe anki.exe"))
    {
        MsgBox("AutoHotkey script is running! Process ID: " . ProcessExist() . "`nAnki process found - SendMessage ready!`n`nHotkeys:`nCtrl+Shift+A = Show Answer (Spacebar)`nCtrl+Z = Again (1 key)`nCtrl+X = Good (3 key)")
    }
    else
    {
        MsgBox("AutoHotkey script is running! Process ID: " . ProcessExist() . "`nWarning: Anki process not found!")
    }
}