; AutoHotkey v2 Script for Anki Global Hotkeys
; Generated by Anki Global Hotkey Card Control addon

; Global hotkeys for Anki card review
; These work regardless of which window has focus using ControlSend

; Ctrl+Z -> Score card as Good
^z::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send F13 key directly to Anki using ControlSend (works in background)
        ControlSend("{F13}", , "ahk_exe anki.exe")
    }
}

; Ctrl+X -> Score card as Again
^x::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Send F14 key directly to Anki using ControlSend (works in background)
        ControlSend("{F14}", , "ahk_exe anki.exe")
    }
}

; Exit hotkey for cleanup (Ctrl+Alt+Q)
^!q::ExitApp()

; Test hotkey for debugging (Ctrl+Alt+T)
^!t::
{
    ; Send a simple message box to verify AHK is working
    MsgBox("AutoHotkey script is running! Process ID: " . ProcessExist())
}