; AutoHotkey v2 Script for Anki Global Hotkeys
; Generated by Anki Global Hotkey Card Control addon

; Global hotkeys for Anki card review
; These work regardless of which window has focus

; Ctrl+Z -> Score card as Good
^z::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Activate Anki window
        WinActivate("ahk_exe anki.exe")
        ; Wait briefly for window activation
        Sleep(50)
        ; Send F13 key which Anki will catch with Qt shortcuts
        Send("{F13}")
    }
    return
}

; Ctrl+X -> Score card as Again
^x::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Activate Anki window
        WinActivate("ahk_exe anki.exe")
        ; Wait briefly for window activation
        Sleep(50)
        ; Send F14 key which Anki will catch with Qt shortcuts
        Send("{F14}")
    }
    return
}

; Ctrl+O -> Toggle always on top
^o::
{
    ; Check if Anki is running
    if (WinExist("ahk_exe anki.exe"))
    {
        ; Activate Anki window
        WinActivate("ahk_exe anki.exe")
        ; Wait briefly for window activation
        Sleep(50)
        ; Send F15 key which Anki will catch with Qt shortcuts
        Send("{F15}")
    }
    return
}

; Exit hotkey for cleanup (Ctrl+Alt+Q)
^!q::ExitApp()